### ISSUE TITLE
Integration worked once, now not at all

### ISSUE THREAD

**Issue by xion92** [thomasloven/hass_plejd#46]
Got this up and running.
After what I think was a normal restart it doesn't work anymore.

Devices is discovered, but is all unavailable

Logs say NOTHING!!

Home assistant 2023.10.1
OS 10.5
RPI 3B+

Have tried: 
Reloading integration.
Removing integration
Removing files from custom_components
Loaded an old backup from before I installed it the first time

*Edit*
The problem seems to be that the plejd-mesh is not auto discovered.
Logs still says nothing

**Comment by oyvindwe** [comment]
Have you enabled bluetooth logging as well? If not, try:
```
logger:
  default: warning
  logs:
    custom_components.plejd: debug
    homeassistant.components.bluetooth: debug
    pyplejd: debug
```
